#!/usr/bin/env python3
"""Rebuild VA-34 source data from the authoritative compilation PDF.

Usage:
  python tools/build-rules-source.py path/to/компиляция ВА34.pdf

The script intentionally does not contain copied source text. It extracts the
PDF at build time and generates rules-source-data.js for the encyclopedia.
"""
from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

START_MARKERS = ["Вдохновение Астрала. Расы"]
END_MARKERS = ["Список родов войск", "Технологии"]
OUT = Path("rules-source-data.js")


def extract_pdf(pdf: Path) -> str:
    pdftotext = shutil.which("pdftotext")
    if not pdftotext:
        raise SystemExit("Не найден pdftotext. Установите Poppler/pdftotext.")
    result = subprocess.run(
        [pdftotext, "-layout", str(pdf), "-"],
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    return result.stdout.replace("\r\n", "\n").replace("\r", "\n")


def validate(text: str) -> None:
    missing = [m for m in START_MARKERS + END_MARKERS if m not in text]
    if missing:
        raise SystemExit("Источник не прошёл проверку; отсутствуют маркеры: " + ", ".join(missing))

    start = min(text.index(m) for m in START_MARKERS)
    ends = [text.index(m, start) for m in END_MARKERS if m in text and text.index(m, start) > start]
    if not ends:
        raise SystemExit("Не найдена граница окончания раздела рас.")
    race_section = text[start:min(ends)]
    if len(race_section) < 1000:
        raise SystemExit("Раздел рас подозрительно короткий; генерация отменена.")


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("Использование: python tools/build-rules-source.py <source.pdf>")
    pdf = Path(sys.argv[1])
    if not pdf.is_file():
        raise SystemExit(f"Файл не найден: {pdf}")

    text = extract_pdf(pdf)
    validate(text)

    OUT.write_text(
        "// Generated by tools/build-rules-source.py. Do not edit manually.\n"
        "window.VA34_RULES_SOURCE = "
        + json.dumps(text, ensure_ascii=False)
        + ";\n",
        encoding="utf-8",
    )
    start = text.index(START_MARKERS[0])
    print(f"OK: extracted {len(text):,} characters")
    print(f"Race section starts at extracted offset {start:,}")
    print(f"Generated: {OUT}")


if __name__ == "__main__":
    main()
